# Generated by Django 2.2.7 on 2019-11-15 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job',
        ),
    ]
