# Generated by Django 2.2.6 on 2019-10-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_date', models.DateField()),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
